### ISSUE TITLE
Tech debt: Use real env values in e2e testing enivornment

### ISSUE THREAD

**Issue by BCerki** [button-inc/digital_marketplace#113]
Tech debt: let's run something like [Sendria](https://github.com/msztolcman/sendria) so these configured values are real within the testing environment.

_Originally posted by @wenzowski in https://github.com/button-inc/digital_marketplace/pull/112#discussion_r774120135_

**Comment by wenzowski** [comment]
s/real env values/valid SMTP env values/

**Comment by BCerki** [comment]
Combining with this issue: https://github.com/button-inc/digital_marketplace/issues/120 and closing
