### ISSUE TITLE
Branching Model Team Agreement

### ISSUE THREAD

**Issue by wenzowski** [button-inc/digital_marketplace#14]
A place to start on a few branching model team agreements to consider adopting:

- Be as lightweight as possible in our approach, and only focus on adopting team agreements that will add value to our [future selves](https://xkcd.com/1597/).
- Adopt the `main` branch as our [default branch](https://github.com/button-inc/digital_marketplace/settings/branches).
- Agree never to commit directly on `main` under any circumstances, and implement [branch protection rules](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches) as a guardrail to enforce the agreement, including enforcement to administrators of this repo.
- Make draft pull requests early and often to facilitate a transparent process.
- Ruthlessly delete branches that aren't tied directly to an open pull request.
- Adopt [Conventional Commits](https://www.conventionalcommits.org/en/) standard for commit messages, and consider authoring commit messages using [Commitizen](http://commitizen.github.io/cz-cli/) to make the spec easier while ensuring notes [stay informative](https://xkcd.com/1296/).
- Follow [peer review best practices](https://google.github.io/eng-practices/review/reviewer/standard.html) by suggesting opportunities to improve code during peer review, merging as soon as the code is *better* than the code in the target branch and [release ready](https://trunkbaseddevelopment.com/observed-habits/#always-release-ready).
- Treat any opportunity for improvement feedback identified during peer review but not implemented in the PR where it was raised as technical debt worthy of a new issue referencing the PR where the comments first came up.
- Commit finalized agreements in `docs/branching_model.md` as a living document, to ensure any decision can be updated as and when required.

**Comment by kriscooke** [comment]
I would like to second each of these motions above ✅

**Comment by BCerki** [comment]
Thirded
