### ISSUE TITLE
Configure SonarCloud

### ISSUE THREAD

**Issue by wenzowski** [button-inc/digital_marketplace#15]
I see Sonar is [leaving comments on PRs](https://github.com/button-inc/digital_marketplace/pull/11). Should we consider adapting https://github.com/bcgov/digital_marketplace/pull/187 to work with [the button SonarCloud instance](https://sonarcloud.io/summary/overall?id=button-inc_digital_marketplace) to tune those messages based on the needs of the team (& our future selves)?

**Comment by BCerki** [comment]
Done in settings
