### ISSUE TITLE
Branch Cleanup

### ISSUE THREAD

**Issue by wenzowski** [button-inc/digital_marketplace#16]
We've got a wicked number of branches in this repo. Would it make sense to clean them up? I personally find 102 active branches a bit much to navigate. Relates to https://github.com/button-inc/digital_marketplace/issues/14

**Comment by wenzowski** [comment]
If the solution to this is to delete, then scripting would be a good idea.

Check out all the branches locally:
```bash
remote=origin ; for brname in `git branch -r | grep $remote | grep -v /master | grep -v /HEAD | awk '{gsub(/^[^\/]+\//,"",$1); print $1}'`; do git branch --track $brname $remote/$brname || true; done 2>/dev/null
```

See everything not yet merged to main:
```bash
git branch --merged | egrep -v "(^\*|main|skip_branch_name_of_open_pr_1|skip_branch_2)"
```

When satisfied the branch list to delete is correct:
```bash
<command of list to delete from prior step> | xargs -rt git push origin --delete # delete remote branches
<command of list to delete from prior step> | xargs -rt git branch -d # delete local branches
```

**Comment by BryanGK** [comment]
CLOSED - completed branch cleanup. From 114 branches to 16 branches.
