### ISSUE TITLE
Definition of Done

### ISSUE THREAD

**Issue by wenzowski** [button-inc/digital_marketplace#19]
Since the pull request peer review process is centred around evaluating our teammates work against our development team definition of done, maybe we should draft this agreement as a [pull request template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates)?

**Comment by wenzowski** [comment]
And maybe our definition of ready should be an issue template?

**Comment by BCerki** [comment]
This sounds great
