### ISSUE TITLE
Follow up improvements to documentation of branching model

### ISSUE THREAD

**Issue by kriscooke** [button-inc/digital_marketplace#21]
Follow up on some typos and elaboration as discussed [in this review](https://github.com/button-inc/digital_marketplace/pull/18#pullrequestreview-820977561).

**Comment by kriscooke** [comment]
Along with the typo suggestions above, `[issue#]-brief description` may be more clear to indicate replacement, or show an example, to not be confused with prefixing with "issue":

Like this: `8-update-sass`
Not this: ~`issue#8-update-sass`~

**Comment by wenzowski** [comment]
In addition to the above referenced thread on #18 (thanks @kriscooke) perhaps this discussion should include [discussion of what behaviours conventions provoke](https://github.com/button-inc/digital_marketplace/pull/18#discussion_r761323747)? Adopting a branch naming convention that begins with the ticket number strongly encourages the team to always make an issue before making a branch/PR. Is this always necessary in our new workflow?

**Comment by BCerki** [comment]
Would also like to discuss requesting a particular reviewer vs. marking as ready for review, especially days when Mike isn't here

**Comment by wenzowski** [comment]
I'd lean towards [creating a `@button-inc/digital_marketplace` team on GitHub](https://docs.github.com/en/organizations/organizing-members-into-teams/creating-a-team) and [making the entire Button development team the CODEOWNERS of this entire fork](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners). That doesn't solve for everything

> especially days when Mike isn't here

but it would ensure the act of requesting review is automated by a guardrail.

**Comment by mikevespi** [comment]
@wenzowski do we have a team in github already that includes all of our devs? When I try to search for button-inc in the settings to give permissions, nothing comes up

**Comment by BCerki** [comment]
Changes to branching agreement are merged in. Since we're moving back to the bcgov repo, fork codeowners is no longer relevant.
