### ISSUE TITLE
Fixing eslint rule errors

### ISSUE THREAD

**Issue by BryanGK** [button-inc/digital_marketplace#37]
ref #25

As a developer, I want to fix the errors from eslint in order of priority, so that we can get the health of the codebase to a manageable level.

DoD:
- eslint errors fixed in order of priority
- a list of errors that are difficult/impossible to fix and the reason why

**Comment by BCerki** [comment]
The three big ones are:
`"no-undef": "off"`
`"no-fallthrough": "off"`--addressed in https://github.com/button-inc/digital_marketplace/pull/40
`"no-duplicate-case": "off"`--addressed in https://github.com/button-inc/digital_marketplace/pull/41
