### ISSUE TITLE
Prettier to run on local pre-commit

### ISSUE THREAD

**Issue by BryanGK** [button-inc/digital_marketplace#39]
ref #27 

As a developer, I want prettier to run on every commit locally with the pre-commit hook, so that I can be sure that I'm submitting properly formatted code.

DoD:
- commit formatted code changes by running prettier against the entire codebase (@wenzowski still a bit unclear as to when this step needs to happen, should it be a separate issue?)
- prettier runs on the pre-commit hook on every commit

**Comment by wenzowski** [comment]
> commit formatted code changes by running prettier against the entire codebase

I'd say [this CI guardrail is configured](https://results.pre-commit.ci/run/github/409311093/1638577626.ZJp0MeZnTmCEeV_JgGZOeg).

**Comment by BCerki** [comment]
Combined with https://github.com/button-inc/digital_marketplace/issues/27
