### ISSUE TITLE
Upgrade Node version to LTS

### ISSUE THREAD

**Issue by kriscooke** [button-inc/digital_marketplace#4]
See [LTS support schedule](https://nodejs.org/en/about/releases/) for reference

**Comment by wenzowski** [comment]
probably do this before #6

**Comment by BryanGK** [comment]
From the node docs [Link](https://nodejs.org/en/about/releases/):

>After 6 months, odd-numbered releases (9, 11, etc.) become unsupported, and even-numbered releases (10, 12, etc.) move to Active LTS status and are ready for general use. LTS release status is "long-term support", which typically guarantees that critical bugs will be fixed for a total of 30 months

With this info I think we should go to Node 16 as our version for this project as Node 17 will likely be unsupported as early as next May.
