### ISSUE TITLE
Capture user stories in cypress test layout

### ISSUE THREAD

**Issue by mikevespi** [button-inc/digital_marketplace#47]
Start laying out the cypress tests by walking through the 3 main paths users will take:
- Crating a new project
- Applying for a project
- Awarding a project

Currently the curation process takes place outside of this app so it can be omitted from this for now.

Just go through and set up the appropriate "it" statements in a way that captures the above.

**Comment by BCerki** [comment]
Additionally write the full test for gov user creating a CWU opportunity

**Comment by BCerki** [comment]
This issue will be broken into smaller issues for individual tests
