### ISSUE TITLE
Setup pre-commit

### ISSUE THREAD

**Issue by mikevespi** [button-inc/digital_marketplace#7]
We decided on using precommit: https://pre-commit.com/
To include:
- ES lint
- detect secrets

**Comment by wenzowski** [comment]
Maybe we should check out the sso-keycloak [pre-commit.yml](https://github.com/bcgov/sso-keycloak/blob/dev/.github/workflows/pre-commit.yml) and [.pre-commit-config.yaml](https://github.com/bcgov/sso-keycloak/blob/dev/.pre-commit-config.yaml)?

**Comment by wenzowski** [comment]
@BCerki proposed splitting GitHub action enforcing pre-commit from this issue. @BryanGK would that change your plans for #13 at all?

**Comment by BryanGK** [comment]
> @BCerki proposed splitting GitHub action enforcing pre-commit from this issue. @BryanGK would that change your plans for #13 at all?

@wenzowski I don't think so, as my changes are for pre-commit on your local machine

**Comment by wenzowski** [comment]
Perfect, let's adopt that split then. Issue breakdown for the win! 🥇
