### ISSUE TITLE
More docs on commitlint

### ISSUE THREAD

**Issue by BCerki** [button-inc/digital_marketplace#74]
Shiny. Any notes for commit message authoring experience introduced by alessandrojcm/commitlint-pre-commit-hook that we should document? What's the developer experience if we write a non-conformant commit message with this hook turned on?

_Originally posted by @wenzowski in https://github.com/button-inc/digital_marketplace/pull/62#pullrequestreview-827138180_

**Comment by BryanGK** [comment]
CLOSED - work completed by #80
