### ISSUE TITLE
Login via Github and IDIR in browser codespaces

### ISSUE THREAD

**Issue by BryanGK** [button-inc/digital_marketplace#94]
### Description
As a developer
I want to be able to login via keycloak thru GitHub and IDIR
So that I can develop for the Digital Marketplace without being tied to an IDE
### Tasks (How)
- [ ] Determine if feasible to login via keycloak in codespace browser
- [ ] Implement code to facilitate logging in with GitHub and IDIR

**Comment by BCerki** [comment]
Codespaces doesn't currently support this
